[shell]
program = 'pwsh.exe'
args = ['-WorkingDirectory', '~']

[font]
size = 14
# normal = { family = 'FiraCode Nerd Font Mono', style = 'Regular' }
normal = { family = 'CozetteVector' }

[window]
padding = { x = 5, y = 5 }
# opacity = 0.92

